version: '3'

services:
  # web-server:
  #   build:
  #     context: .
  #     dockerfile: ./server/Dockerfile
  #   ports:
  #     - "8080:1323"
  #   volumes:
  #     - ./server/:/go/src
  #   depends_on:
  #     - db
  recorder:
    build:
      context: .
      dockerfile: ./recorder/Dockerfile
    depends_on:
      - db
    tty: true
    volumes:
      - .:/go/src
  db:
    image: influxdb:2.6
    container_name: db
    environment:
      - INFLUX_HOST="http://db:8086"
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my_org
      - DOCKER_INFLUXDB_INIT_BUCKET=climate
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myadmintoken

    ports: 
      - "8086:8086"
    volumes:
      - ./db/influxdb/data/influxdb2:/var/lib/influxdb2
      - ./db/influxdb/data/config:/etc/influxdb2
  broker:
    container_name: broker
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mqtt_dashboard_mysql_data:
  grafana_data:
